namespace NexusLabs.Narnia.Core.Services;

/// <summary>
/// Generates a VBScript launcher that starts a process hidden from the moment it is created.
/// </summary>
public static class HiddenProcessLauncherScript
{
    /// <summary>
    /// Builds a <c>WScript.Shell.Run</c> launcher using window style <c>0</c> so no console window
    /// is displayed or briefly flashed.
    /// </summary>
    /// <param name="commandLine">Complete command line to launch.</param>
    /// <param name="workingDirectory">Optional working directory assigned before launch.</param>
    /// <param name="waitForExit">Whether the launcher waits for and forwards the child exit code.</param>
    /// <returns>Self-contained VBScript launcher content.</returns>
    public static string Build(
        string commandLine,
        string? workingDirectory,
        bool waitForExit)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(commandLine);

        var commandLiteral = EscapeVbScriptString(commandLine);
        var waitLiteral = waitForExit ? "True" : "False";
        var workingDirectoryLine = string.IsNullOrWhiteSpace(workingDirectory)
            ? ""
            : $"shell.CurrentDirectory = \"{EscapeVbScriptString(workingDirectory)}\"\r\n";

        return
            "' Auto-generated by Narnia. Do not edit this file.\r\n" +
            "Set shell = CreateObject(\"WScript.Shell\")\r\n" +
            workingDirectoryLine +
            $"exitCode = shell.Run(\"{commandLiteral}\", 0, {waitLiteral})\r\n" +
            "WScript.Quit exitCode\r\n";
    }

    private static string EscapeVbScriptString(string value) =>
        value.Replace("\"", "\"\"");
}
