namespace NexusLabs.Narnia.Core.Services;

/// <summary>
/// Generates the self-contained VBScript shim that makes a Narnia-owned scheduled job run
/// completely headless. Windows Task Scheduler has no "hidden window" action setting of its own,
/// and PowerShell's own <c>-WindowStyle Hidden</c> is well known to still flash a console window
/// briefly on some systems (the window is created visible, then hidden a moment later). Launching
/// through <c>wscript.exe</c> and <c>WScript.Shell.Run</c> with window style <c>0</c> avoids that
/// entirely: the process is created hidden from the start, so no window — not even a flash — is
/// ever shown. <c>bWaitOnReturn=True</c> makes the launcher block until the wrapper script exits and
/// forwards its exit code, so Task Scheduler's last-run-result still reflects the real outcome.
/// </summary>
public static class ScheduledJobLauncherScript
{
    /// <summary>
    /// Builds the VBScript launcher content. <paramref name="hostExecutable"/> is the PowerShell
    /// host to run <paramref name="scriptPath"/> under (see <see cref="IPowerShellHostResolver"/>).
    /// </summary>
    public static string Build(string hostExecutable, string scriptPath)
    {
        var commandLine = $"{hostExecutable} -NoProfile -ExecutionPolicy Bypass -File \"{scriptPath}\"";
        var vbsLiteral = commandLine.Replace("\"", "\"\"");
        return
            "' Auto-generated by Narnia. Edit the job in the Narnia UI, not this file.\r\n" +
            "Set shell = CreateObject(\"WScript.Shell\")\r\n" +
            $"exitCode = shell.Run(\"{vbsLiteral}\", 0, True)\r\n" +
            "WScript.Quit exitCode\r\n";
    }
}
