using System.Text;

namespace NexusLabs.Narnia.Core.Services;

/// <summary>
/// Generates the self-contained PowerShell wrapper that a Narnia-owned scheduled job runs. The
/// wrapper is what makes a job first-class: it invokes <c>copilot -p</c> with the job's prompt,
/// sets the working directory, and captures output to a per-run log — so Narnia never has to edit
/// a user's own scripts. The prompt is embedded in a single-quoted here-string so arbitrary text
/// (quotes, <c>$</c>, backticks) is passed verbatim with no injection surface.
/// </summary>
public static class ScheduledJobScript
{
    /// <summary>Builds the wrapper script content for a job.</summary>
    /// <param name="name">Display name, written to the log header.</param>
    /// <param name="prompt">The prompt passed to <c>copilot -p</c>.</param>
    /// <param name="workingDirectory">Directory to run in, or <c>null</c> to inherit.</param>
    /// <param name="allowFlags">Copilot allow-flags (e.g. <c>--allow-all-tools --allow-all-paths</c>).</param>
    /// <param name="copilotArgs">Extra arguments appended to the copilot invocation, or <c>null</c>.</param>
    /// <param name="logDirectory">Directory the wrapper writes per-run logs to.</param>
    public static string Build(
        string name,
        string prompt,
        string? workingDirectory,
        string? allowFlags,
        string? copilotArgs,
        string logDirectory)
    {
        var extra = new StringBuilder();
        if (!string.IsNullOrWhiteSpace(allowFlags))
            extra.Append(' ').Append(allowFlags.Trim());
        if (!string.IsNullOrWhiteSpace(copilotArgs))
            extra.Append(' ').Append(copilotArgs.Trim());

        var sb = new StringBuilder();
        sb.AppendLine("# Auto-generated by Narnia. Edit the job in the Narnia UI, not this file.");
        sb.AppendLine("$ErrorActionPreference = 'Continue'");
        sb.AppendLine($"$logDir = '{EscapeSingle(logDirectory)}'");
        sb.AppendLine("if (-not (Test-Path $logDir)) { New-Item -ItemType Directory -Path $logDir -Force | Out-Null }");
        sb.AppendLine("$log = Join-Path $logDir (\"run-\" + (Get-Date -Format 'yyyy-MM-dd_HHmmss') + \".log\")");
        sb.AppendLine($"\"=== {EscapeDouble(name)} ===\" | Tee-Object -FilePath $log | Out-Null");
        sb.AppendLine("\"Start: $(Get-Date -Format o)\" | Tee-Object -FilePath $log -Append | Out-Null");

        if (!string.IsNullOrWhiteSpace(workingDirectory))
            sb.AppendLine($"Set-Location -LiteralPath '{EscapeSingle(workingDirectory)}'");

        sb.AppendLine("$prompt = @'");
        // Single-quoted here-string: content is literal. The only terminator is a line that is
        // exactly '@, so a prompt line can never accidentally close it.
        foreach (var line in prompt.Replace("\r\n", "\n").Split('\n'))
            sb.AppendLine(line);
        sb.AppendLine("'@");

        sb.AppendLine($"& copilot -p $prompt{extra} 2>&1 | ForEach-Object {{ \"$($_.ToString())\" }} | Tee-Object -FilePath $log -Append");
        sb.AppendLine("$code = if ($null -ne $LASTEXITCODE) { $LASTEXITCODE } else { 0 }");
        sb.AppendLine("\"End: $(Get-Date -Format o) ExitCode: $code\" | Tee-Object -FilePath $log -Append | Out-Null");
        sb.AppendLine("exit $code");
        return sb.ToString();
    }

    private static string EscapeSingle(string value) => value.Replace("'", "''");

    private static string EscapeDouble(string value) => value.Replace("`", "``").Replace("\"", "`\"").Replace("$", "`$");
}
