<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTrimmable>true</IsTrimmable>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="System.IO.Abstractions" />
    <PackageReference Include="dbup-sqlite" />
    <PackageReference Include="YamlDotNet" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Repositories\Migrations\*.sql" />
  </ItemGroup>

</Project>
